language: java
install: true
jdk:
  - oraclejdk8

branches:
  only:
  - master
  
script: mvn -Denv=dev clean test coveralls:report
  
after_success:  
  - mvn clean test jacoco:report coveralls:report
  